name: Generate Version

on:
  push:
    branches:
      - '**'

jobs:
  generate-version:
    runs-on: ubuntu-latest

    env:
      APP_VERSION: 4.5.24

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get branch name
        id: vars
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get short commit hash
        id: commit
        run: echo "short_commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Determine branch key and name
        id: branchkey
        run: |
          BRANCH="${{ env.branch_name }}"
          if [[ "$BRANCH" == release/* ]]; then
            echo "branch_key=REL" >> $GITHUB_ENV
            echo "branch_specific=${BRANCH#release/}" >> $GITHUB_ENV
          elif [[ "$BRANCH" == integration/* ]]; then
            echo "branch_key=INT" >> $GITHUB_ENV
            echo "branch_specific=${BRANCH#integration/}" >> $GITHUB_ENV
          elif [[ "$BRANCH" == hotfix/* ]]; then
            echo "branch_key=HTX" >> $GITHUB_ENV
            echo "branch_specific=${BRANCH#hotfix/}" >> $GITHUB_ENV
          elif [[ "$BRANCH" == master ]]; then
            echo "branch_key=master" >> $GITHUB_ENV
            echo "branch_specific=master" >> $GITHUB_ENV
          else
            echo "branch_key=" >> $GITHUB_ENV
            echo "branch_specific=$BRANCH" >> $GITHUB_ENV
          fi

      - name: Generate version string
        id: version
        run: |
          if [[ "${{ env.branch_key }}" != "" ]]; then
            VERSION_STRING="${{ env.APP_VERSION }}-${{ env.branch_key }}-${{ env.branch_specific }}-${{ env.short_commit }}-${{ github.run_attempt }}"
          else
            VERSION_STRING="${{ env.APP_VERSION }}-${{ github.run_id }}-${{ github.run_attempt }}"
          fi
          echo "version_string=$VERSION_STRING" >> $GITHUB_ENV

      - name: Output version string
        run: echo "Generated version string:${{ env.version_string }}"
