name: Deploy

on:
  push:
    branches:
      - 'REL'
      - 'master'
      - 'HTX'
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up variables
        id: vars
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          COMMIT_HASH=${GITHUB_SHA:0:7}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          
          if [[ $BRANCH_NAME == release/* ]]; then
            BRANCH_KEY="REL"
          elif [[ $BRANCH_NAME == integration/* ]]; then
            BRANCH_KEY="INT"
          elif [[ $BRANCH_NAME == hotfix/* ]]; then
            BRANCH_KEY="HTX"
          elif [[ $BRANCH_NAME == master ]]; then
            BRANCH_KEY="master"
          else
            BRANCH_KEY=""
          fi
          
          echo "BRANCH_KEY=$BRANCH_KEY" >> $GITHUB_ENV

      - name: Retrieve incremental number from GitHub API
        id: get-incremental
        run: |
          # Fetch the current value of the variable
          RESPONSE=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/INCREMENTAL-${BRANCH_NAME})
          
          echo "Response: $RESPONSE"
          
          # Parse the JSON response to get the variable value
          INCREMENTAL=$(echo $RESPONSE | jq -r '.value')
          
          # If the variable doesn't exist, initialize it to 0
          if [[ "$INCREMENTAL" == "null" ]]; then
            INCREMENTAL=0
          fi
          
          # Increment the value
          INCREMENTAL=$((INCREMENTAL + 1))
          
          echo "INCREMENTAL=$INCREMENTAL" >> $GITHUB_ENV
          
      - name: Construct version string
        run: |
          APP_VERSION="4.5.24"
          if [[ -n $BRANCH_KEY ]]; then
            VERSION="$APP_VERSION-$BRANCH_KEY-$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9]//g')-$COMMIT_HASH-$INCREMENTAL"
          else
            VERSION="$APP_VERSION-${GITHUB_RUN_ID}-$INCREMENTAL"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Display version
        run: echo "Version: ${{ env.VERSION }}"

      - name: Update incremental number in GitHub API
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/INCREMENTAL-${BRANCH_NAME} \
            -d "{\"value\":\"${INCREMENTAL}\"}"
