name: Increment Version Number

on:
  push:
    branches:
      - master
      - release/*
      - integration/*
      - hotfix/*
      - "**"

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch Incremental Number
        id: fetch-increment
        run: |
          # Fetch the .increment file from the repository
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/Swamy-Pepakayala/versioning/contents/.increment?ref=master \
               -o increment.json
          # Extract content and decode from base64
          FILE_CONTENT=$(jq -r '.content' increment.json)
          INCREMENT=$(echo "$FILE_CONTENT" | base64 -d)
          echo "INCREMENT=$INCREMENT" >> $GITHUB_ENV

      - name: Increment Number
        id: increment
        run: |
          # Increment the number
          CURRENT_INCREMENT=${{ env.INCREMENT }}
          NEW_INCREMENT=$(( CURRENT_INCREMENT + 1 ))

          # Write the new increment value to a file
          echo $NEW_INCREMENT > .increment

          # Encode the new increment file content to base64
          base64 .increment | tr -d '\n' > new_increment.b64
          echo "NEW_INCREMENT=$NEW_INCREMENT" >> $GITHUB_ENV

      - name: Update Incremental Number
        run: |
          # Fetch the SHA of the existing .increment file
          FILE_SHA=$(jq -r '.sha' increment.json)
          
          # Update the .increment file in the repository
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -d "{\"message\":\"Update increment number\",\"content\":\"$(cat new_increment.b64)\",\"sha\":\"$FILE_SHA\"}" \
               https://api.github.com/repos/Swamy-Pepakayala/versioning/contents/.increment?ref=master

      - name: Generate Version String
        id: generate-version
        run: |
          APP_VERSION="4.5.24"
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          BRANCH_KEY="UNKNOWN"
          if [[ "$BRANCH_NAME" == release* ]]; then
            BRANCH_KEY="REL"
          elif [[ "$BRANCH_NAME" == integration* ]]; then
            BRANCH_KEY="INT"
          elif [[ "$BRANCH_NAME" == hotfix* ]]; then
            BRANCH_KEY="HTX"
          elif [[ "$BRANCH_NAME" == master ]]; then
            BRANCH_KEY="master"
          fi
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          RUN_ATTEMPT=${{ github.run_attempt }}
          if [[ "$BRANCH_KEY" == "UNKNOWN" ]]; then
            VERSION_STRING="${APP_VERSION}-${{ github.run_id }}-${RUN_ATTEMPT}-${{ env.NEW_INCREMENT }}"
          else
            VERSION_STRING="${APP_VERSION}-${{ env.BRANCH_KEY }}-${BRANCH_NAME}-${SHORT_COMMIT_HASH}-${RUN_ATTEMPT}-${{ env.NEW_INCREMENT }}"
          fi
          echo "VERSION_STRING=$VERSION_STRING" >> $GITHUB_ENV

      - name: Display Version String
        run: echo "Version String is ${{ env.VERSION_STRING }}"
