name: Generate Version

on:
  push:
    branches:
      - '**'

jobs:
  generate-version:
    runs-on: ubuntu-latest

    env:
      APP_VERSION: 4.5.24
      INCREMENT_FILE: .increment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git fetch --prune --unshallow
          git config --global --add safe.directory /github/workspace

      - name: Get branch name
        id: vars
        run: echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"
        shell: bash

      - name: Get short commit hash
        id: commit
        run: echo "::set-output name=short_commit::$(git rev-parse --short HEAD)"
        shell: bash

      - name: Determine branch key and name
        id: branchkey
        run: |
          BRANCH=${{ steps.vars.outputs.branch_name }}
          if [[ "$BRANCH" == release/* ]]; then
            echo "::set-output name=branch_key::REL"
            echo "::set-output name=branch_specific::${BRANCH#release/}"
          elif [[ "$BRANCH" == integration/* ]]; then
            echo "::set-output name=branch_key::INT"
            echo "::set-output name=branch_specific::${BRANCH#integration/}"
          elif [[ "$BRANCH" == hotfix/* ]]; then
            echo "::set-output name=branch_key::HTX"
            echo "::set-output name=branch_specific::${BRANCH#hotfix/}"
          elif [[ "$BRANCH" == master ]]; then
            echo "::set-output name=branch_key::master"
            echo "::set-output name=branch_specific::master"
          else
            echo "::set-output name=branch_key::"
            echo "::set-output name=branch_specific::$BRANCH"
          fi
        shell: bash

      - name: Incremental number setup
        id: increment
        run: |
          if [ ! -f ${{ env.INCREMENT_FILE }} ]; then echo 0 > ${{ env.INCREMENT_FILE }}; fi
          LAST_INCREMENT=$(cat ${{ env.INCREMENT_FILE }})
          NEW_INCREMENT=$((LAST_INCREMENT + 1))
          echo $NEW_INCREMENT > ${{ env.INCREMENT_FILE }}
          echo "::set-output name=incremental_number::$NEW_INCREMENT"
        shell: bash

      - name: Generate version string
        id: version
        run: |
          if [[ "${{ steps.branchkey.outputs.branch_key }}" != "" ]]; then
            VERSION_STRING="${{ env.APP_VERSION }}-${{ steps.branchkey.outputs.branch_key }}-${{ steps.branchkey.outputs.branch_specific }}-${{ steps.commit.outputs.short_commit }}-${{ steps.increment.outputs.incremental_number }}"
          else
            VERSION_STRING="${{ env.APP_VERSION }}-${{ github.run_id }}-${{ steps.increment.outputs.incremental_number }}"
          fi
          echo "::set-output name=version_string::$VERSION_STRING"
        shell: bash

      - name: Output version string
        run: echo "Generated version string: ${{ steps.version.outputs.version_string }}"

      - name: Persist incremental number
        uses: actions/upload-artifact@v2
        with:
          name: increment-file
          path: ${{ env.INCREMENT_FILE }}
