name: Deploy

on:
  push:
    branches:
      - 'REL'
      - 'master'
      - 'HTX'
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up variables
        id: vars
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          COMMIT_HASH=${GITHUB_SHA:0:7}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          
          if [[ $BRANCH_NAME == release/* ]]; then
            BRANCH_KEY="REL"
          elif [[ $BRANCH_NAME == integration/* ]]; then
            BRANCH_KEY="INT"
          elif [[ $BRANCH_NAME == hotfix/* ]]; then
            BRANCH_KEY="HTX"
          elif [[ $BRANCH_NAME == master ]]; then
            BRANCH_KEY="master"
          else
            BRANCH_KEY=""
          fi
          
          echo "BRANCH_KEY=$BRANCH_KEY" >> $GITHUB_ENV
          
      - name: Get previous incremental number
        id: get-incremental
        run: |
          # Define cache directory
          CACHE_DIR="${GITHUB_WORKSPACE}/.github/incremental"
          mkdir -p $CACHE_DIR
          
          # Create cache key
          BRANCH_CACHE_KEY=$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9]//g')
          echo "BRANCH_CACHE_KEY=$BRANCH_CACHE_KEY" >> $GITHUB_ENV
          
          # Define cache file path
          CACHE_FILE="$CACHE_DIR/${BRANCH_CACHE_KEY}.incremental"
          
          # Read or initialize incremental number
          if [[ -f $CACHE_FILE ]]; then
            INCREMENTAL=$(cat $CACHE_FILE)
            INCREMENTAL=$((INCREMENTAL + 1))
          else
            INCREMENTAL=1
          fi
          
          # Save new incremental number
          echo $INCREMENTAL > $CACHE_FILE
          echo "INCREMENTAL=$INCREMENTAL" >> $GITHUB_ENV


      - name: Construct version string
        run: |
          APP_VERSION="4.5.24"
          if [[ -n $BRANCH_KEY ]]; then
            VERSION="$APP_VERSION-$BRANCH_KEY-$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9]//g')-$COMMIT_HASH-$INCREMENTAL"
          else
            VERSION="$APP_VERSION-${GITHUB_RUN_ID}-$INCREMENTAL"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Display version
        run: echo "Version:${{ env.VERSION }}"

      - name: Save incremental number
        if: success()
        uses: actions/cache@v3
        with:
          path: .github/workflows/
          key: ${{ runner.os }}-incremental-${{ env.BRANCH_CACHE_KEY }}
