name: branching version

on:
  push:
    branches:
      - master
      - release/*
      - integration/*
      - hotfix/*
      - feature/*
      - '*'

jobs:
  generate-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set Branch Key
      id: set-key
      run: |
        BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
        if [[ "$BRANCH_NAME" == release* ]]; then
          echo "BRANCH_KEY=REL" >> $GITHUB_ENV
        elif [[ "$BRANCH_NAME" == integration* ]]; then
          echo "BR
